### ISSUE TITLE
Missing assets?

### ISSUE THREAD

**Issue by elhoyos** [nmoore32/Space-Invaders-Clone#2]
After manually installing all? the dependencies I get these errors:
```bash
jim@annita:~/tmp/Space-Invaders-Clone$ pip install pygame
Collecting pygame
  Downloading https://files.pythonhosted.org/packages/8e/24/ede6428359f913ed9cd1643dd5533aefeb5a2699cc95bea089de50ead586/pygame-1.9.6-cp36-cp36m-manylinux1_x86_64.whl (11.4MB)
    100% |████████████████████████████████| 11.4MB 167kB/s
Installing collected packages: pygame
Successfully installed pygame-1.9.6
You are using pip version 9.0.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
jim@annita:~/tmp/Space-Invaders-Clone$ python demo.py
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "demo.py", line 5, in <module>
    from constants import FPS
  File "/home/jim/tmp/Space-Invaders-Clone/constants.py", line 27, in <module>
    ALIEN_IMG_1 = pygame.image.load('images/alien1a.bmp')
pygame.error: Couldn't open images/alien1a.bmp
```

After a bundle attempt:
```bash
jim@annita:~/tmp/Space-Invaders-Clone$ python setup.py build_exe
running build_exe
Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    executables=executables
  File "/home/jim/.pyenv/versions/3.6.2/lib/python3.6/site-packages/cx_Freeze/dist.py", line 340, in setup
    distutils.core.setup(**attrs)
  File "/home/jim/.pyenv/versions/3.6.2/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/jim/.pyenv/versions/3.6.2/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/jim/.pyenv/versions/3.6.2/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/jim/.pyenv/versions/3.6.2/lib/python3.6/site-packages/cx_Freeze/dist.py", line 210, in run
    zipExcludePackages = self.zip_exclude_packages)
  File "/home/jim/.pyenv/versions/3.6.2/lib/python3.6/site-packages/cx_Freeze/freezer.py", line 105, in __init__
    self._VerifyConfiguration()
  File "/home/jim/.pyenv/versions/3.6.2/lib/python3.6/site-packages/cx_Freeze/freezer.py", line 460, in _VerifyConfiguration
    sourceFileName)
cx_Freeze.freezer.ConfigError: cannot find file/directory named images/alien1a.bmp
```

What am I doing wrong?

**Comment by nmoore32** [comment]
The game assets (images and sound files) were missing. I've now added them.
